blank_issues_enabled: false
contact_links:
  - name: 🌟 Valorar la app en Google Play
    url: https://play.google.com/store/apps/details?id=com.egeainc.kioskeo
    about: Si te gusta Kioskeo, dejanos una reseña
  - name: 📧 Contacto directo
    url: mailto:gabriel600r@gmail.com
    about: Para temas privados o comerciales
